//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadDetail
    {
        public int LeadDetailsId { get; set; }
        public int ProfessionalId { get; set; }
        public int CustomerId { get; set; }
        public int SubCategoryId { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public Nullable<int> CreditUsed { get; set; }
        public Nullable<System.DateTime> GeneratedDateTime { get; set; }
        public string LeadStatus { get; set; }
        public string OrderDesc { get; set; }
        public string CompletedSpareParts { get; set; }
        public string TotalCost { get; set; }
        public string DeniedReason { get; set; }
    }
}
