//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Price { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
