//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquacareWebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProfessional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerProfessional()
        {
            this.IsNotificationShowns = new HashSet<IsNotificationShown>();
            this.OrderRequests = new HashSet<OrderRequest>();
            this.OrderWithProfessionals = new HashSet<OrderWithProfessional>();
            this.RechargeOrders = new HashSet<RechargeOrder>();
            this.ServiceProvideds = new HashSet<ServiceProvided>();
            this.LeadDetails = new HashSet<LeadDetail>();
        }
    
        public int PartnerProfessionalId { get; set; }
        public string PartnerName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MobileNo { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<int> PincodeId { get; set; }
        public Nullable<int> Cityid { get; set; }
        public string Ratings { get; set; }
        public string TotalIncome { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsNotificationShown> IsNotificationShowns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderWithProfessional> OrderWithProfessionals { get; set; }
        public virtual Pincode Pincode { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RechargeOrder> RechargeOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProvided> ServiceProvideds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadDetail> LeadDetails { get; set; }
    }
}
