//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquacareWebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvided
    {
        public int ServiceProvidedId { get; set; }
        public int PartnerId { get; set; }
        public int SubCategoryId { get; set; }
    
        public virtual PartnerProfessional PartnerProfessional { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
